language: csharp
dotnet: 3.1
mono: alpha
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe
script:
- dotnet test Test/Test.csproj
- mono .nuget/nuget.exe pack -NoDefaultExcludes
deploy:
- provider: releases
  skip_cleanup: true
  api_key: "$git_token"
  file_glob: true
  file: "*.nupkg"
  on:
    tags: true