language: csharp
script:
  - dotnet test Test/Test.csproj
deploy:
  script: nuget pack -NoDefaultExcludes && nuget push "$(find . -name '*.nupkg')" $APIKEY -Source $PACKAGE_SOURCE
  on:
    branch: master
    tags: true
