branches:
  only:
  - master
language: csharp
script:
  - dotnet test Test/Test.csproj
deploy:
  on:
    tag: true
    script: nuget pack -NoDefaultExcludes && nuget push "$(find . -name '*.nupkg')" $APIKEY -Source $PACKAGE_SOURCE
