pr:
  - master
trigger:
  branches:
    include:
    - master
    - refs/tags/v*
pool:
  vmImage: ubuntu-latest

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Test/Test.csproj'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Microsoft.Azure.IoT.Edge.Module.nuspec'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: GitHubRelease@0
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  inputs:
    gitHubConnection: 'github.com_marianan'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: '$(Build.SourceBranch)'
    releaseNotesSource: 'input'
    isPreRelease: true
    addChangeLog: false