pr:
  - master
trigger:
  branches:
    include:
    - master
    - refs/tags/v*
pool:
  vmImage: ubuntu-latest

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Test/Test.csproj'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Microsoft.Azure.IoT.Edge.Module.nuspec'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'IoT Edge NuGet Sign - DDE'
    FolderPath: '$(Build.ArtifactStagingDirectory)'
    Pattern: '*.nupkg'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [ 
          {
              "keyCode": "CP-401405",
              "operationSetCode": "NuGetSign",
              "parameters": [ ],
              "toolName": "sign",
              "toolVersion": "1.0"
          },
          {
              "keyCode": "CP-401405",
              "operationSetCode": "NuGetVerify",
              "parameters": [ ],
              "toolName": "sign",
              "toolVersion": "1.0"
          }
      ]
    SessionTimeout: '20'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
- task: GitHubRelease@0
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  inputs:
    gitHubConnection: 'github.com_marianan'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: '$(Build.SourceBranch)'
    releaseNotesSource: 'input'
    isPreRelease: false
    addChangeLog: false

- task: PowerShell@1
  displayName: 'PowerShell Script'
  inputs:
    scriptType: 'inlineScript'
    arguments: '-apikey $(api_key)'
    workingFolder: '$(Build.ArtifactStagingDirectory)'
    inlineScript: |
      param($apikey)
      echo $env:BUILD_SOURCEBRANCH
      if ($env:BUILD_SOURCEBRANCH -match "^refs/tags/v?[0-9]+\.[0-9]+\.[0-9]+$") {
          echo "starting NuGet Push"
          nuget push *.nupkg $apikey -Source https://api.nuget.org/v3/index.json
      } else {
          echo "skipping NuGet Push"
      }