pool:
  vmImage: ubuntu-latest

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Test/Test.csproj'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Microsoft.Azure.IoT.Edge.Module.nuspec'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

