FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime-alpine
WORKDIR /app
COPY --from=build-env /app/out ./

RUN adduser -Ds /bin/sh moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "SampleModule.dll"]