FROM microsoft/dotnet:2.0-sdk AS build-env
WORKDIR /app

COPY *.fsproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.0-runtime-stretch-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "SampleModule.dll"]