FROM microsoft/dotnet:2.1-sdk-nanoserver-1803 AS build-env
WORKDIR /app

COPY *.fsproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime-nanoserver-1803
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "SampleModule.dll"]