name: CI
on: [push]
  #push:
    #branches:
     # - master
    #tags:
     # - v*.*.*
  #pull_request:
   # branches:
    #  - master

jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p .nuget
      - run: >-
          wget -O .nuget/nuget.exe
          https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      - run: mono .nuget/nuget.exe
      - run: dotnet test Test/Test.csproj
      - run: mono .nuget/nuget.exe pack -NoDefaultExcludes
      - name: GitHub Release
        if: |
           success() &&
           startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
            files: ./**/*.nupkg   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tags: true
